name: Release
on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
          version: 7.30.3

      # - name: Derive appropriate SHAs for base and head for `nx affected` commands
      #   uses: nrwl/nx-set-shas@v2
      #   with:
      #     main-branch-name: ${{ github.base_ref }}

      - name: Install Dependencies
        run: pnpm install

      # - run: |
      #     npx nx affected --target lint --parallel 3
      #     npx nx affected --target test --parallel 3 --ci --code-coverage
      #     npx nx run-many --target build

      - name: 'Bump version'
        run: node ./bump-version.mjs
        shell: bash
      # - run: echo "VERSION_JSON=$(jq -c . < version.json)" >> $GITHUB_ENV
      # - run: echo 'VERSION=${{ fromJson(env.VERSION_JSON).version }}' >> $GITHUB_ENV
      # - run: echo 'VERSION = ${{env.VERSION}}'
      # - run: echo "`jq '.base_config[1].value="1.2.14"' config.json`" > config.json

      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: |
      #     npx nx run-many --target release
