name: Release
on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
          version: 7.30.3

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{ github.base_ref }}

      - name: Install Dependencies
        run: pnpm install

        # npx nx affected --target lint --parallel 3
      - name: Lint, test and build
        run: |
          npx nx affected --target test --parallel 3 --ci --code-coverage
          npx nx run-many -t build

      - name: Configure Git
        run: |
          git config --global user.email "ci@widgets.teliacompany.com"
          git config --global user.name "CI"

      - name: 🔑 Authenticate with NPM
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN  }}' > ~/.npmrc
          echo '//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          cat ~/.npmrc

      - name: 'Bump version'
        run: node ./bump-version.mjs
        shell: bash

      - name: 'Release'
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN  }}' > ~/.npmrc
          echo '//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          npx nx run-many -t publish

      - name: 'Commit changes'
        run: |
          git add version.json
          git commit -m "Release"
          git push
